#!/bin/bash

# Dependencies:
# imagemagick
# i3lock-color-git
# scrot

IMAGE=/tmp/i3lock.png

# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x8" # 7.52s
#BLURTYPE="0x5" # 7.52s
#BLURTYPE="0x2" # 4.39s
#BLURTYPE="5x3" # 3.80s
#BLURTYPE="2x8" # 2.90s
#BLURTYPE="2x3" # 2.92s

scrot $IMAGE

convert $IMAGE \
  -filter Gaussian \
  -resize 50% \
  -define \
    filter:sigma=3.10 \
  -resize 200% \
  $IMAGE

~/.i3/i3lock-color \
	--textcolor=ffffff00 \
	--insidecolor=ffffff1c \
	--ringcolor=ffffff3e \
	--linecolor=ffffff00 \
	--keyhlcolor=00000080 \
	--ringvercolor=00000000 \
	--insidevercolor=66CCFF1c \
	--ringwrongcolor=ff000055 \
	--insidewrongcolor=ff00001c \
	-i $IMAGE

rm $IMAGE
